# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b0ba354b13867381a7b246445de809d48209fee01e355e250d9bbc3c661d2f48816eb06c5e6cc0f0d3cb81872c771f9666fb56f1dfc7f80b497b234927e30eb8

test:
  secret_key_base: c7950b485d69f6f59d8399ec036ed6e62435225670c1b7edb599fd7b9cdfd3e02a0bbf4c5500565295b74cee2e36b8cdefb82f2c25f6507d538528ea873aefae

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
